/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScoreValue = IDL.Nat;
export const Timestamp = IDL.Int;
export const Category = IDL.Text;
export const Score = IDL.Record({
  'score' : ScoreValue,
  'timestamp' : Timestamp,
  'playerName' : IDL.Text,
  'category' : Category,
});

export const idlService = IDL.Service({
  'getAllScores' : IDL.Func([], [IDL.Vec(Score)], ['query']),
  'getCategoryLeaderboard' : IDL.Func([Category], [IDL.Vec(Score)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(Score)], ['query']),
  'submitScore' : IDL.Func([IDL.Text, ScoreValue, Category], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScoreValue = IDL.Nat;
  const Timestamp = IDL.Int;
  const Category = IDL.Text;
  const Score = IDL.Record({
    'score' : ScoreValue,
    'timestamp' : Timestamp,
    'playerName' : IDL.Text,
    'category' : Category,
  });
  
  return IDL.Service({
    'getAllScores' : IDL.Func([], [IDL.Vec(Score)], ['query']),
    'getCategoryLeaderboard' : IDL.Func(
        [Category],
        [IDL.Vec(Score)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(Score)], ['query']),
    'submitScore' : IDL.Func([IDL.Text, ScoreValue, Category], [], []),
  });
};

export const init = ({ IDL }) => { return []; };